### ISSUE TITLE
Choice of number of years

### ISSUE THREAD

**Issue by OrkoHunter** [anujmenta/papercop#1]
By default, users get question papers of three years. We can also ask them to input how much they need (e.g. 2 yrs, 5 yrs) and then return fetching from whatever we have in our database. If they don't give any input, it'll be same as the default.
How good is it?

**Comment by anujmenta** [comment]
That's already incorporated in the system which is not functional now due to some maintenence issues. It was up for v1.0 but was silenced for the latest version. However we plan to add that back next time. 

Thank you !
